### ISSUE TITLE
Resize settings

### ISSUE THREAD

**Issue by ribaraka** [instaclustr/operator#514]
The v2 API introduced a new field that sets resize settings. Should we provide this feature for customers?
https://instaclustr.redoc.ly/Current/tag/Apache-Kafka-Provisioning-V2#paths/~1cluster-management~1v2~1resources~1applications~1kafka~1clusters~1v2~1{clusterId}/put!path=resizeSettings&t=request

**Comment by testisnullus** [comment]
I think yes, we just need to add an additional field to our cluster specs. Seems like a pretty easy task
