### ISSUE TITLE
Implement an OpenSearch Egress Rules lifecycle workflow on APIv2

### ISSUE THREAD

**Issue by testisnullus** [instaclustr/operator#522]
Instaclustr released an OpenSearch Egress Rules V2 - https://instaclustr.redoc.ly/Current/tag/OpenSearch-Egress-Rules-V2, so we need to implement the whole lifecycle of this product via our Instaclustr Operator

**Comment by ribaraka** [comment]
merged https://github.com/instaclustr/operator/pull/527
