### ISSUE TITLE
Backup not found

### ISSUE THREAD

**Issue by ribaraka** [instaclustr/operator#530]
fix a bug
![image](https://github.com/instaclustr/operator/assets/74422582/af7c5f63-6d97-45c1-945b-bf6f5d97ec1d)

a possible way to reproduce the bug:
1. create a cluster.
2. obtain a backup resource from the cluster (e.g. `kubectl get clusterbackups.clusterresources.instaclustr.com`).
3. delete the cluster in UI.

**Comment by tengu-alt** [comment]
i can't reproduce it yet
