### ISSUE TITLE
[User CRD] New finilizer to a deleting resource

### ISSUE THREAD

**Issue by ribaraka** [instaclustr/operator#532]
Our current logic ensures that when a user is attached to a cluster, a finalizer is added to the user to keep it from accidental removal and ensure healthy work. The flaw is when (accidentally) deleting a User with finalizers and you still want to work with the same user, there will be an issue to add the user yet to another cluster, k8s doesn’t allow adding new finalizers to deleting resources.

**Comment by worryg0d** [comment]
It doesn't look like a bug, it's common k8s behavior when the resource is being deleted. Even kubectl reports when someone tries to update a resource in this state.
But for better UX maybe this is a good idea to omit adding those cluster-specific finalizers.
