### ISSUE TITLE
Integrate Monitoring API

### ISSUE THREAD

**Issue by ribaraka** [instaclustr/operator#578]
https://instaclustr.redoc.ly/Current/tag/Monitoring-API

**Comment by testisnullus** [comment]
Monitoring API doesn't provide a convenient and flexible way to retrieve critically essential metrics for customer clusters, so we decided to use integration with Prometheus. Regarding the Instaclustr documentation customers can easily retrieve Prometheus metrics for their clusters or even the whole account by adding a small configuration to the prometheus.yml file - https://www.instaclustr.com/support/api-integrations/integrations/instaclustr-monitoring-with-prometheus/

It's suggested to add the reference to the mentioned documentation and config sample itself to the operator documentation and let customers decide what clusters should be monitored.

**Comment by ribaraka** [comment]
This needs to be doced
