### ISSUE TITLE
Extract the UserRef CRUD flow from predicates

### ISSUE THREAD

**Issue by ribaraka** [instaclustr/operator#607]
We have CRUD operations of the User resources implemented in the predicate funcs. Probably not a good flow for handling CRUD operations. If possible, need to invent a better approach

**Comment by worryg0d** [comment]
PR #616 which implements it for Cassandra was merged

**Comment by ribaraka** [comment]
Implement for Postgres

**Comment by ribaraka** [comment]
pg user management is going to be remove at all
