### ISSUE TITLE
Test Cassandra cluster resource

### ISSUE THREAD

**Issue by testisnullus** [instaclustr/operator#650]
We need to test all Cassandra spec fields, and settings, check their workability, create/update/delete operations, add/remove data centers, etc.

Create separate issues for all bugs found during the test process. If not, add your comment on what was tested and the results in this issue.

**Comment by testisnullus** [comment]
Related issue - https://github.com/instaclustr/operator/issues/649

**Comment by OleksiienkoMykyta** [comment]
During testing Cassandra resource, I found issue with Kafka datacentre. When we using Kafka datacentre, we need to enable schemaRegistry, but there are no available versions for it, I wrote about it to team customer platform, and they respond that schema registry and rest proxy are all in closed state, can`t be used for new cluster provicioning. We can use Karapace instead.
