### ISSUE TITLE
Test Postgres cluster resource

### ISSUE THREAD

**Issue by ribaraka** [instaclustr/operator#659]
We need to test all Postgres spec fields, and settings, check their workability, create/update/delete operations, add/remove data centers, etc.

Create separate issues for all bugs found during the test process. If not, add your comment on what was tested and the results in this issue.

- [x] #662
- [x] #729

**Comment by worryg0d** [comment]
I found the following issues:
* The operator allows updating `dataCentres.interDataCentreReplication.isPrimaryDataCentre` field, but when an update request is sent to the Instaclustr API it returns a response with status code 400 and says that the update is not supported.
* With `dataCentres.intraDataCentreReplication.replicationMode` the same story. Also, the operator allows to set any value to the field but only `ASYNCHRONOUS` and `SYNCHRONOUS` are available.
* Customers may update `clusterConfigurations` via Instaclustr Console, but the operator doesn't handle changes for `clusterConfigurations` field. It should drop to external changes state

**Comment by worryg0d** [comment]
- [ ] make `dataCentres.interDataCentreReplication` and  `dataCentres.intraDataCentreReplication` immutable during resource update
- [ ] handle external changes of `clusterConfiguration`
