### ISSUE TITLE
Move code not related to status check to other places

### ISSUE THREAD

**Issue by RostislavPorohnya** [instaclustr/operator#661]
In Cassandra status checker job we have operations not related to the update status process.
We need to move these operations to other jobs or places.
Issue related to all clusters, not only Cassandra.

Unneeded operations in Cassandra status job:
- [ ] Create expose service
- [ ] Check spec difference
- [ ] Handle node replace for on-premises clusters

**Comment by ribaraka** [comment]
decided to give a different name to the job. Now it is SyncJob
